// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyForms.Data;

#nullable disable

namespace PharmacyForms.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220210194658_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PharmacyForms.Models.EndOfDayModel", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<double>("AlternativeAdjudications")
                        .HasColumnType("float");

                    b.Property<double>("AlternativeCogs")
                        .HasColumnType("float");

                    b.Property<double>("ApprovedPatientCount")
                        .HasColumnType("float");

                    b.Property<double>("Cogs")
                        .HasColumnType("float");

                    b.Property<double>("DeniedPatientCount")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExistingPatientCount")
                        .HasColumnType("float");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HighCopayCount")
                        .HasColumnType("float");

                    b.Property<decimal>("InsuranceAdjudications")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("InsuranceErrors")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceTerminatedCount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NotContractedCount")
                        .HasColumnType("float");

                    b.Property<string>("OtherExceptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PatientExceptionCount")
                        .HasColumnType("float");

                    b.Property<double>("RefillAdjudications")
                        .HasColumnType("float");

                    b.Property<double>("RefillCogs")
                        .HasColumnType("float");

                    b.Property<double>("RxCount")
                        .HasColumnType("float");

                    b.Property<double>("RxRefills")
                        .HasColumnType("float");

                    b.Property<double>("TransferredPatientCount")
                        .HasColumnType("float");

                    b.Property<double>("WrongDOBCount")
                        .HasColumnType("float");

                    b.Property<double>("WrongLastNameCount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("EndOfDay");
                });

            modelBuilder.Entity("PharmacyForms.Models.PatientCountModel", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientCount")
                        .HasColumnType("int");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
